name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Print Cargo version
        run: cargo --version
      - name: Print Rust version
        run: rustc --version
      - name: Check formatting
        run: cargo fmt --verbose --all -- --check
      - name: Clippy
        run: cargo clippy --verbose --workspace --tests
      - name: Build
        run: cargo build --verbose --workspace --tests
      - name: Test
        run: cargo test --verbose --workspace --tests
